export enum HciOgf {
  LinkControlCommands                   = 0x01,
  LinkPolicyCommands                    = 0x02,
  ControlAndBasebandCommands            = 0x03,
  InformationParameters                 = 0x04,
  StatusParameters                      = 0x05,
  TestingCommands                       = 0x06,
  LeControllerCommands                  = 0x08,
}

export enum HciOcfLinkControlCommands {
  // TODO
}

export enum HicOcfLinkPolicyCommands {
  // TODO
}

export enum HciOcfControlAndBasebandCommands {
  SetEventMask                          = 0x0001,
  Reset                                 = 0x0003,
  SetEventFilter                        = 0x0005,
  Flush                                 = 0x0008,
  ReadPinType                           = 0x0009,
  WritePinType                          = 0x000A,
  ReadStoredLinkKey                     = 0x000D,
  WriteStoredLinkKey                    = 0x0011,
  DeleteStoredLinkKey                   = 0x0012,
  WriteLocalName                        = 0x0013,
  ReadLocalName                         = 0x0014,
  ReadConnectionAcceptTimeout           = 0x0015,
  WriteConnectionAcceptTimeout          = 0x0016,
  ReadPageTimeout                       = 0x0017,
  WritePageTimeout                      = 0x0018,
  ReadScanEnable                        = 0x0019,
  WriteScanEnable                       = 0x001A,
  ReadPageScanActivity                  = 0x001B,
  WritePageScanActivity                 = 0x001C,
  ReadInquiryScanActivity               = 0x001D,
  WriteInquiryScanActivity              = 0x001E,
  ReadAuthenticationEnable              = 0x001F,
  WriteAuthenticationEnable             = 0x0020,
  ReadClassOfDevice                     = 0x0023,
  WriteClassOfDevice                    = 0x0024,
  ReadVoiceSetting                      = 0x0025,
  WriteVoiceSetting                     = 0x0026,
  ReadAutomaticFlushTimeout             = 0x0027,
  WriteAutomaticFlushTimeout            = 0x0028,
  ReadNumBroadcastRetransmissions       = 0x0029,
  WriteNumBroadcastRetransmissions      = 0x002A,
  ReadHoldModeActivity                  = 0x002B,
  WriteHoldModeActivity                 = 0x002C,
  ReadTransmitPowerLevel                = 0x002D,
  ReadSynchronousFlowControlEnable      = 0x002E,
  WriteSynchronousFlowControlEnable     = 0x002F,
  SetControllerToHostFlowControl        = 0x0031,
  HostBufferSize                        = 0x0033,
  HostNumberOfCompletedPackets          = 0x0035,
  ReadLinkSupervisionTimeout            = 0x0036,
  WriteLinkSupervisionTimeout           = 0x0037,
  ReadNumberOfSupportedIac              = 0x0038,
  ReadCurrentIacLap                     = 0x0039,
  WriteCurrentIacLap                    = 0x003A,
  SetAfhHostChannelClassification       = 0x003F,
  ReadInquiryScanType                   = 0x0042,
  WriteInquiryScanType                  = 0x0043,
  ReadInquiryMode                       = 0x0044,
  WriteInquiryMode                      = 0x0045,
  ReadPageScanType                      = 0x0046,
  WritePageScanType                     = 0x0047,
  ReadAfhChannelAssessmentMode          = 0x0048,
  WriteAfhChannelAssessmentMode         = 0x0049,
  ReadExtendedInquiryResponse           = 0x0051,
  WriteExtendedInquiryResponse          = 0x0052,
  RefreshEncryptionKey                  = 0x0053,
  ReadSimplePairingMode                 = 0x0055,
  WriteSimplePairingMode                = 0x0056,
  ReadLocalOOBData                      = 0x0057,
  ReadInquiryResponseTransmitPowerLevel = 0x0058,
  WriteInquiryTransmitPowerLevel        = 0x0059,
  SendKeypressNotification              = 0x0060,
  ReadDefaultErroneousDataReporting     = 0x005A,
  WriteDefaultErroneousDataReporting    = 0x005B,
  EnhancedFlush                         = 0x005F,
  ReadLogicalLinkAcceptTimeout          = 0x0061,
  WriteLogicalLinkAcceptTimeout         = 0x0062,
  SetEventMaskPage2                     = 0x0063,
  ReadLocationData                      = 0x0064,
  WriteLocationData                     = 0x0065,
  ReadFlowControlMode                   = 0x0066,
  WriteFlowControlMode                  = 0x0067,
  ReadEnhancedTransmitPowerLevel        = 0x0068,
  ReadBestEffortFlushTimeout            = 0x0069,
  WriteBestEffortFlushTimeout           = 0x006A,
  ShortRangeMode                        = 0x006B,
  ReadLeHostSupport                     = 0x006C,
  WriteLeHostSupport                    = 0x006D,
  SetMwsChannelParameters               = 0x006E,
  SetExternalFrameConfiguration         = 0x006F,
  SetMwsSignaling                       = 0x0070,
  SetMwsTransportLayer                  = 0x0071,
  SetMwsScanFrequencyTable              = 0x0072,
  SetMwsPatternConfiguration            = 0x0073,
  SetReservedLtAddr                     = 0x0074,
  DeleteReservedLtAddr                  = 0x0075,
  SetConnectionlessSlaveBroadcastData   = 0x0076,
  ReadSynchronizationTrainParameters    = 0x0077,
  WriteSynchronizationTrainParameters   = 0x0078,
  ReadSecureConnectionsHostSupport      = 0x0079,
  WriteSecureConnectionsHostSupport     = 0x007A,
  ReadAuthenticatedPayloadTimeout       = 0x007B,
  WriteAuthenticatedPayloadTimeout      = 0x007C,
  ReadLocalOobExtendedData              = 0x007D,
  ReadExtendedPageTimeout               = 0x007E,
  WriteExtendedPageTimeout              = 0x007F,
  ReadExtendedInquiryLength             = 0x0080,
  WriteExtendedInquiryLength            = 0x0081,
  SetEcosystemBaseInterval              = 0x0082,
  ConfigureDataPath                     = 0x0083,
}

export enum HciOcfInformationParameters {
  ReadLocalVersionInformation           = 0x0001,
  ReadLocalSupportedCommands            = 0x0002,
  ReadLocalSupportedFeatures            = 0x0003,
  ReadLocalExtendedFeatures             = 0x0004,
  ReadBufferSize                        = 0x0005,
  ReadBdAddr                            = 0x0009,
  ReadDataBlockSize                     = 0x000A,
  ReadLocalSupportedCodecsV1            = 0x000B,
  ReadLocalSupportedCodecsV2            = 0x000D,
  ReadLocalSimplePairingOptions         = 0x000C,
  ReadLocalSupportedCodecCapabilities   = 0x000E,
  ReadLocalSupportedControllerDelay     = 0x000F,
}
